// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRPGServer.Data;

#nullable disable

namespace TRPGServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250610013306_FixCharacterIssue")]
    partial class FixCharacterIssue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TRPGServer.Entity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("TRPGServer.Entity.Character.CharacterBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("APP")
                        .HasColumnType("int");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CON")
                        .HasColumnType("int");

                    b.Property<int>("DEX")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("EDU")
                        .HasColumnType("int");

                    b.Property<string>("Era")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("INT")
                        .HasColumnType("int");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("LUCK")
                        .HasColumnType("int");

                    b.Property<int>("MP")
                        .HasColumnType("int");

                    b.Property<int>("Mov")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<int>("POW")
                        .HasColumnType("int");

                    b.Property<int>("SAN")
                        .HasColumnType("int");

                    b.Property<int>("SIZ")
                        .HasColumnType("int");

                    b.Property<int>("STR")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ImageId");

                    b.ToTable("CharacterBase");
                });

            modelBuilder.Entity("TRPGServer.Entity.Character.CharacterItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DiceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("DiceId");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("TRPGServer.Entity.Character.CharacterStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterStatus");
                });

            modelBuilder.Entity("TRPGServer.Entity.Class.ClassBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("APP")
                        .HasColumnType("int");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CON")
                        .HasColumnType("int");

                    b.Property<int>("DEX")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("EDU")
                        .HasColumnType("int");

                    b.Property<string>("Era")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("INT")
                        .HasColumnType("int");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("LUCK")
                        .HasColumnType("int");

                    b.Property<int>("MP")
                        .HasColumnType("int");

                    b.Property<int>("Mov")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<int>("POW")
                        .HasColumnType("int");

                    b.Property<int>("SAN")
                        .HasColumnType("int");

                    b.Property<int>("SIZ")
                        .HasColumnType("int");

                    b.Property<int>("STR")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("ClassBase");
                });

            modelBuilder.Entity("TRPGServer.Entity.Class.ClassItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClassBaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DiceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassBaseId");

                    b.HasIndex("DiceId");

                    b.ToTable("ClassItems");
                });

            modelBuilder.Entity("TRPGServer.Entity.Class.ClassStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClassBaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassBaseId");

                    b.ToTable("ClassStatus");
                });

            modelBuilder.Entity("TRPGServer.Entity.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageBase64")
                        .IsRequired()
                        .HasColumnType("MEDIUMTEXT");

                    b.HasKey("Id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.ActiveCharacter.RoomCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("APP")
                        .HasColumnType("int");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CON")
                        .HasColumnType("int");

                    b.Property<int>("DEX")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("EDU")
                        .HasColumnType("int");

                    b.Property<string>("Era")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("INT")
                        .HasColumnType("int");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("LUCK")
                        .HasColumnType("int");

                    b.Property<int>("MP")
                        .HasColumnType("int");

                    b.Property<int>("Mov")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<int>("POW")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SAN")
                        .HasColumnType("int");

                    b.Property<int>("SIZ")
                        .HasColumnType("int");

                    b.Property<int>("STR")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ImageId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomCharacter");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.ActiveCharacter.RoomCharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DiceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomCharacterId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiceId");

                    b.HasIndex("RoomCharacterId");

                    b.ToTable("RoomCharacterItem");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.ActiveCharacter.RoomCharacterStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoomCharacterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomCharacterId");

                    b.ToTable("RoomCharacterStatus");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.Dice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Dice");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.GameType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GameType");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.PlaySet.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.PlaySet.RoomActor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomActor");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.PlaySet.RoomChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomChat");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.PlaySet.RoomLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomLog");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.RoomSet.RoomRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomRule");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.RoomSet.RoomTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<bool>("VisiableToPlayer")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomTemplate");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.RoomSet.TemplateDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoomTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<bool>("VisiableToPlayer")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("RoomTemplateId");

                    b.ToTable("TemplateDetail");
                });

            modelBuilder.Entity("TRPGServer.Entity.Story", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("RoomId");

                    b.ToTable("Story");
                });

            modelBuilder.Entity("TRPGServer.Entity.Character.CharacterBase", b =>
                {
                    b.HasOne("TRPGServer.Entity.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRPGServer.Entity.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Account");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TRPGServer.Entity.Character.CharacterItems", b =>
                {
                    b.HasOne("TRPGServer.Entity.Character.CharacterBase", "CharacterBase")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRPGServer.Entity.RoomObject.Dice", "Dice")
                        .WithMany()
                        .HasForeignKey("DiceId");

                    b.Navigation("CharacterBase");

                    b.Navigation("Dice");
                });

            modelBuilder.Entity("TRPGServer.Entity.Character.CharacterStatus", b =>
                {
                    b.HasOne("TRPGServer.Entity.Character.CharacterBase", "CharacterBase")
                        .WithMany("Status")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterBase");
                });

            modelBuilder.Entity("TRPGServer.Entity.Class.ClassBase", b =>
                {
                    b.HasOne("TRPGServer.Entity.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TRPGServer.Entity.Class.ClassItems", b =>
                {
                    b.HasOne("TRPGServer.Entity.Class.ClassBase", "ClassBase")
                        .WithMany("Items")
                        .HasForeignKey("ClassBaseId");

                    b.HasOne("TRPGServer.Entity.RoomObject.Dice", "Dice")
                        .WithMany()
                        .HasForeignKey("DiceId");

                    b.Navigation("ClassBase");

                    b.Navigation("Dice");
                });

            modelBuilder.Entity("TRPGServer.Entity.Class.ClassStatus", b =>
                {
                    b.HasOne("TRPGServer.Entity.Class.ClassBase", "ClassBase")
                        .WithMany("Status")
                        .HasForeignKey("ClassBaseId");

                    b.Navigation("ClassBase");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.ActiveCharacter.RoomCharacter", b =>
                {
                    b.HasOne("TRPGServer.Entity.RoomObject.PlaySet.RoomActor", "RoomActor")
                        .WithMany("Characters")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRPGServer.Entity.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("TRPGServer.Entity.RoomObject.Room", "Room")
                        .WithMany("Characters")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Room");

                    b.Navigation("RoomActor");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.ActiveCharacter.RoomCharacterItem", b =>
                {
                    b.HasOne("TRPGServer.Entity.RoomObject.Dice", "Dice")
                        .WithMany()
                        .HasForeignKey("DiceId");

                    b.HasOne("TRPGServer.Entity.RoomObject.ActiveCharacter.RoomCharacter", "RoomCharacter")
                        .WithMany("Items")
                        .HasForeignKey("RoomCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dice");

                    b.Navigation("RoomCharacter");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.ActiveCharacter.RoomCharacterStatus", b =>
                {
                    b.HasOne("TRPGServer.Entity.RoomObject.ActiveCharacter.RoomCharacter", "RoomCharacter")
                        .WithMany("Status")
                        .HasForeignKey("RoomCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomCharacter");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.Dice", b =>
                {
                    b.HasOne("TRPGServer.Entity.RoomObject.GameType", "GameType")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.PlaySet.Note", b =>
                {
                    b.HasOne("TRPGServer.Entity.RoomObject.PlaySet.RoomActor", "RoomActor")
                        .WithMany("Notes")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomActor");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.PlaySet.RoomActor", b =>
                {
                    b.HasOne("TRPGServer.Entity.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRPGServer.Entity.RoomObject.Room", "Room")
                        .WithMany("Actors")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.PlaySet.RoomChat", b =>
                {
                    b.HasOne("TRPGServer.Entity.RoomObject.Room", "Room")
                        .WithMany("Chat")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.PlaySet.RoomLog", b =>
                {
                    b.HasOne("TRPGServer.Entity.RoomObject.Room", "Room")
                        .WithMany("Logs")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.Room", b =>
                {
                    b.HasOne("TRPGServer.Entity.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.RoomSet.RoomRule", b =>
                {
                    b.HasOne("TRPGServer.Entity.RoomObject.Room", "Room")
                        .WithMany("Rules")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.RoomSet.RoomTemplate", b =>
                {
                    b.HasOne("TRPGServer.Entity.RoomObject.Room", "Room")
                        .WithMany("Templates")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.RoomSet.TemplateDetail", b =>
                {
                    b.HasOne("TRPGServer.Entity.RoomObject.RoomSet.RoomTemplate", "RoomTemplate")
                        .WithMany("TemplateDetails")
                        .HasForeignKey("RoomTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomTemplate");
                });

            modelBuilder.Entity("TRPGServer.Entity.Story", b =>
                {
                    b.HasOne("TRPGServer.Entity.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("TRPGServer.Entity.RoomObject.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TRPGServer.Entity.Account", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("TRPGServer.Entity.Character.CharacterBase", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TRPGServer.Entity.Class.ClassBase", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.ActiveCharacter.RoomCharacter", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.PlaySet.RoomActor", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.Room", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Characters");

                    b.Navigation("Chat");

                    b.Navigation("Logs");

                    b.Navigation("Rules");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("TRPGServer.Entity.RoomObject.RoomSet.RoomTemplate", b =>
                {
                    b.Navigation("TemplateDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
